name: 'greenhouse'
version: '1.5.0'
config-version: 2
require-dbt-version: [">=1.3.0", "<3.0.0"]

vars:
  greenhouse:
    activity: "{{ source('greenhouse', 'activity') }}"
    application: "{{ source('greenhouse', 'application') }}"
    department: "{{ source('greenhouse', 'department') }}"
    attachment: "{{ source('greenhouse', 'attachment') }}"
    candidate: "{{ source('greenhouse', 'candidate') }}"
    candidate_tag_link: "{{ source('greenhouse', 'candidate_tag_link') }}"
    application_history: "{{ source('greenhouse', 'application_history') }}"
    eeoc: "{{ source('greenhouse', 'eeoc') }}"
    candidate_email_address: "{{ source('greenhouse', 'candidate_email_address') }}"
    job: "{{ source('greenhouse', 'job') }}"
    job_hiring_manager: "{{ source('greenhouse', 'job_hiring_manager') }}"
    job_office: "{{ source('greenhouse', 'job_office') }}"
    opening: "{{ source('greenhouse', 'opening') }}"
    job_owner: "{{ source('greenhouse', 'job_owner') }}"
    job_post: "{{ source('greenhouse', 'job_post') }}"
    job_interview_stage: "{{ source('greenhouse', 'job_interview_stage') }}"
    office: "{{ source('greenhouse', 'office') }}"
    candidate_phone_number: "{{ source('greenhouse', 'candidate_phone_number') }}"
    prospect_pool: "{{ source('greenhouse', 'prospect_pool') }}"
    prospect_pool_stage: "{{ source('greenhouse', 'prospect_pool_stage') }}"
    interview: "{{ source('greenhouse', 'interview') }}"
    interviewer: "{{ source('greenhouse', 'interviewer') }}"
    scorecard: "{{ source('greenhouse', 'scorecard') }}"
    scorecard_candidate_attribute: "{{ source('greenhouse', 'scorecard_candidate_attribute') }}"
    candidate_social_media_address: "{{ source('greenhouse', 'candidate_social_media_address') }}"
    source: "{{ source('greenhouse', 'source') }}"
    user_email: "{{ source('greenhouse', 'user_email') }}"
    users: "{{ source('greenhouse', 'users') }}"
    candidate_tag: "{{ source('greenhouse', 'candidate_tag') }}"
    job_post_location: "{{ source('greenhouse', 'job_post_location') }}"

models:
  greenhouse:
    +materialized: table
    +schema: greenhouse
    intermediate:
      +materialized: ephemeral
    staging:
      +materialized: table
      +schema: stg_greenhouse
      tmp:
        +materialized: view
