name: 'greenhouse_integration_tests'
version: '1.5.0'
config-version: 2
profile: 'integration_tests'

models:
  +persist_docs:
    relation: true
    columns: "{{ false if target.type in ('databricks') else true }}"
  +schema: "greenhouse_{{ var('directed_schema','dev') }}"

vars:
  greenhouse_schema: zz_dbt_avinash_seed
  greenhouse:
    greenhouse_activity_identifier: "activity"
    greenhouse_application_identifier: "application"
    greenhouse_application_history_identifier: "application_history"
    greenhouse_attachment_identifier: "attachment"
    greenhouse_candidate_identifier: "candidate"
    greenhouse_candidate_tag_link_identifier: "candidate_tag_link"
    greenhouse_department_identifier: "department"
    greenhouse_eeoc_identifier: "eeoc"
    greenhouse_candidate_email_address_identifier: "candidate_email_address"
    greenhouse_job_identifier: "job"
    greenhouse_job_hiring_manager_identifier: "job_hiring_manager"
    greenhouse_job_office_identifier: "job_office"
    greenhouse_opening_identifier: "opening"
    greenhouse_job_owner_identifier: "job_owner"
    greenhouse_job_post_identifier: "job_post"
    greenhouse_job_interview_stage_identifier: "job_interview_stage"
    greenhouse_office_identifier: "office"
    greenhouse_candidate_phone_number_identifier: "candidate_phone_number"
    greenhouse_prospect_pool_identifier: "prospect_pool"
    greenhouse_prospect_pool_stage_identifier: "prospect_pool_stage"
    greenhouse_interview_identifier: "interview"
    greenhouse_interviewer_identifier: "interviewer"
    greenhouse_scorecard_identifier: "scorecard"
    greenhouse_scorecard_candidate_attribute_identifier: "scorecard_candidate_attribute"
    greenhouse_candidate_social_media_address_identifier: "candidate_social_media_address"
    greenhouse_source_identifier: "source"
    greenhouse_candidate_tag_identifier: "candidate_tag"
    greenhouse_rejection_reason_identifier: "rejection_reason"
    greenhouse_users_identifier: "users"
    greenhouse_user_email_identifier: "user_email"

  # Comment out when generating docs
  greenhouse_application_custom_columns: ['custom_what_is_your_preferred_pronoun_', 'custom_how_did_you_hear_about_fivetran_'] # @docs-ignore
  greenhouse_job_custom_columns: ['custom_employment_type', 'custom_stock_options'] # @docs-ignore

seeds:
  +docs:
    show: False
  +quote_columns: "{{ target.type in ('redshift', 'postgres') or var('fivetran_using_source_casing', false) }}"
  greenhouse_integration_tests:
    +column_types:
      _fivetran_synced: timestamp
    activity:
      +column_types:
        created_at: timestamp
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    application:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        coordinator_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_post_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        recruiter_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        referrer_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        agency_note_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        stage_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        source_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        last_activity_at: timestamp
        rejected_at: timestamp
        created_at: timestamp
        updated_at: timestamp
        needs_decision: boolean
    application_history:
      +column_types:
        updated_at: timestamp
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        new_stage_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    attachment:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    candidate:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        last_activity_at: timestamp
        updated_at: timestamp
        private: boolean
        can_email: boolean
    candidate_tag_link:
      +column_types:
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    candidate_email_address:
      +column_types:
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    department:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        parent_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    eeoc:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        disability_status_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        gender_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        race_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        veteran_status_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        submitted_at: timestamp
        created_at: timestamp
        updated_at: timestamp
    job_hiring_manager:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    job_owner:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    interview:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_interview_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        organizer_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
        starts_at: timestamp
        ends_at: timestamp
        scheduled_at: timestamp
        availability_received_at: timestamp
        all_day_start_on: date
        all_day_end_on: date
    job:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        department_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        copied_from_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        closed_at: timestamp
        created_at: timestamp
        updated_at: timestamp
        opened_at: timestamp
        is_template: boolean
    job_interview_stage:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
        active: boolean
        sort_order: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    job_office:
      +column_types:
        office_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        index: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    opening:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        close_reason_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        closed_at: timestamp
        opened_at: timestamp
        target_start_on: date
        is_open: boolean
        sort_order: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    job_post:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_board_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        demographic_question_set_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
        first_published_at: timestamp
        active: boolean
        internal: boolean
        live: boolean
        featured: boolean
    job_post_location:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_post_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        office_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        custom_location_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    office:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        parent_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        primary_in_house_contact_user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        name: "{{ 'string' if target.name in ('bigquery', 'databricks') else 'varchar' }}"
        location: "{{ 'string' if target.name in ('bigquery', 'databricks') else 'varchar' }}"
        created_at: timestamp
        updated_at: timestamp
    candidate_phone_number:
      +column_types:
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    prospect_pool:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    prospect_pool_stage:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        prospect_pool_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
        sort_order: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    interviewer:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        interview_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        scorecard_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    scorecard:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        application_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        submitter_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        interviewer_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        interview_kit_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        interviewed_at: timestamp
        submitted_at: timestamp
        updated_at: timestamp
    scorecard_candidate_attribute:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        scorecard_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        job_candidate_attribute_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    candidate_social_media_address:
      +column_types:
        candidate_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    source:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        source_type_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
    rejection_reason:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        type_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    candidate_tag:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
    users:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
        deactivated: boolean
    user_email:
      +column_types:
        id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        user_id: "{{ 'int64' if target.type == 'bigquery' else 'bigint' }}"
        created_at: timestamp
        updated_at: timestamp
        verified: boolean
        verification_token_sent_at: timestamp

dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']

flags:
  send_anonymous_usage_stats: False
  use_colors: True